# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arthurbrito/ComputerGraphics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arthurbrito/ComputerGraphics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/arthurbrito/ComputerGraphics/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthurbrito/ComputerGraphics/CMakeFiles /home/arthurbrito/ComputerGraphics//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthurbrito/ComputerGraphics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CG_Creto_work

# Build rule for target.
CG_Creto_work: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CG_Creto_work
.PHONY : CG_Creto_work

# fast build rule for target.
CG_Creto_work/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/build
.PHONY : CG_Creto_work/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build.make _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

Algebra.o: Algebra.cpp.o
.PHONY : Algebra.o

# target to build an object file
Algebra.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/Algebra.cpp.o
.PHONY : Algebra.cpp.o

Algebra.i: Algebra.cpp.i
.PHONY : Algebra.i

# target to preprocess a source file
Algebra.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/Algebra.cpp.i
.PHONY : Algebra.cpp.i

Algebra.s: Algebra.cpp.s
.PHONY : Algebra.s

# target to generate assembly for a file
Algebra.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/Algebra.cpp.s
.PHONY : Algebra.cpp.s

bin/Trabalho_Final.o: bin/Trabalho_Final.cpp.o
.PHONY : bin/Trabalho_Final.o

# target to build an object file
bin/Trabalho_Final.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/bin/Trabalho_Final.cpp.o
.PHONY : bin/Trabalho_Final.cpp.o

bin/Trabalho_Final.i: bin/Trabalho_Final.cpp.i
.PHONY : bin/Trabalho_Final.i

# target to preprocess a source file
bin/Trabalho_Final.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/bin/Trabalho_Final.cpp.i
.PHONY : bin/Trabalho_Final.cpp.i

bin/Trabalho_Final.s: bin/Trabalho_Final.cpp.s
.PHONY : bin/Trabalho_Final.s

# target to generate assembly for a file
bin/Trabalho_Final.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/bin/Trabalho_Final.cpp.s
.PHONY : bin/Trabalho_Final.cpp.s

src/Aresta/Aresta.o: src/Aresta/Aresta.cpp.o
.PHONY : src/Aresta/Aresta.o

# target to build an object file
src/Aresta/Aresta.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Aresta/Aresta.cpp.o
.PHONY : src/Aresta/Aresta.cpp.o

src/Aresta/Aresta.i: src/Aresta/Aresta.cpp.i
.PHONY : src/Aresta/Aresta.i

# target to preprocess a source file
src/Aresta/Aresta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Aresta/Aresta.cpp.i
.PHONY : src/Aresta/Aresta.cpp.i

src/Aresta/Aresta.s: src/Aresta/Aresta.cpp.s
.PHONY : src/Aresta/Aresta.s

# target to generate assembly for a file
src/Aresta/Aresta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Aresta/Aresta.cpp.s
.PHONY : src/Aresta/Aresta.cpp.s

src/Camera/Camera.o: src/Camera/Camera.cpp.o
.PHONY : src/Camera/Camera.o

# target to build an object file
src/Camera/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Camera/Camera.cpp.o
.PHONY : src/Camera/Camera.cpp.o

src/Camera/Camera.i: src/Camera/Camera.cpp.i
.PHONY : src/Camera/Camera.i

# target to preprocess a source file
src/Camera/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Camera/Camera.cpp.i
.PHONY : src/Camera/Camera.cpp.i

src/Camera/Camera.s: src/Camera/Camera.cpp.s
.PHONY : src/Camera/Camera.s

# target to generate assembly for a file
src/Camera/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Camera/Camera.cpp.s
.PHONY : src/Camera/Camera.cpp.s

src/Cilindro/Cilindro.o: src/Cilindro/Cilindro.cpp.o
.PHONY : src/Cilindro/Cilindro.o

# target to build an object file
src/Cilindro/Cilindro.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Cilindro/Cilindro.cpp.o
.PHONY : src/Cilindro/Cilindro.cpp.o

src/Cilindro/Cilindro.i: src/Cilindro/Cilindro.cpp.i
.PHONY : src/Cilindro/Cilindro.i

# target to preprocess a source file
src/Cilindro/Cilindro.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Cilindro/Cilindro.cpp.i
.PHONY : src/Cilindro/Cilindro.cpp.i

src/Cilindro/Cilindro.s: src/Cilindro/Cilindro.cpp.s
.PHONY : src/Cilindro/Cilindro.s

# target to generate assembly for a file
src/Cilindro/Cilindro.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Cilindro/Cilindro.cpp.s
.PHONY : src/Cilindro/Cilindro.cpp.s

src/Circulo/Circulo.o: src/Circulo/Circulo.cpp.o
.PHONY : src/Circulo/Circulo.o

# target to build an object file
src/Circulo/Circulo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Circulo/Circulo.cpp.o
.PHONY : src/Circulo/Circulo.cpp.o

src/Circulo/Circulo.i: src/Circulo/Circulo.cpp.i
.PHONY : src/Circulo/Circulo.i

# target to preprocess a source file
src/Circulo/Circulo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Circulo/Circulo.cpp.i
.PHONY : src/Circulo/Circulo.cpp.i

src/Circulo/Circulo.s: src/Circulo/Circulo.cpp.s
.PHONY : src/Circulo/Circulo.s

# target to generate assembly for a file
src/Circulo/Circulo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Circulo/Circulo.cpp.s
.PHONY : src/Circulo/Circulo.cpp.s

src/Cone/Cone.o: src/Cone/Cone.cpp.o
.PHONY : src/Cone/Cone.o

# target to build an object file
src/Cone/Cone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Cone/Cone.cpp.o
.PHONY : src/Cone/Cone.cpp.o

src/Cone/Cone.i: src/Cone/Cone.cpp.i
.PHONY : src/Cone/Cone.i

# target to preprocess a source file
src/Cone/Cone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Cone/Cone.cpp.i
.PHONY : src/Cone/Cone.cpp.i

src/Cone/Cone.s: src/Cone/Cone.cpp.s
.PHONY : src/Cone/Cone.s

# target to generate assembly for a file
src/Cone/Cone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Cone/Cone.cpp.s
.PHONY : src/Cone/Cone.cpp.s

src/Esfera/Esfera.o: src/Esfera/Esfera.cpp.o
.PHONY : src/Esfera/Esfera.o

# target to build an object file
src/Esfera/Esfera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Esfera/Esfera.cpp.o
.PHONY : src/Esfera/Esfera.cpp.o

src/Esfera/Esfera.i: src/Esfera/Esfera.cpp.i
.PHONY : src/Esfera/Esfera.i

# target to preprocess a source file
src/Esfera/Esfera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Esfera/Esfera.cpp.i
.PHONY : src/Esfera/Esfera.cpp.i

src/Esfera/Esfera.s: src/Esfera/Esfera.cpp.s
.PHONY : src/Esfera/Esfera.s

# target to generate assembly for a file
src/Esfera/Esfera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Esfera/Esfera.cpp.s
.PHONY : src/Esfera/Esfera.cpp.s

src/Iluminacao/Iluminacao.o: src/Iluminacao/Iluminacao.cpp.o
.PHONY : src/Iluminacao/Iluminacao.o

# target to build an object file
src/Iluminacao/Iluminacao.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Iluminacao/Iluminacao.cpp.o
.PHONY : src/Iluminacao/Iluminacao.cpp.o

src/Iluminacao/Iluminacao.i: src/Iluminacao/Iluminacao.cpp.i
.PHONY : src/Iluminacao/Iluminacao.i

# target to preprocess a source file
src/Iluminacao/Iluminacao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Iluminacao/Iluminacao.cpp.i
.PHONY : src/Iluminacao/Iluminacao.cpp.i

src/Iluminacao/Iluminacao.s: src/Iluminacao/Iluminacao.cpp.s
.PHONY : src/Iluminacao/Iluminacao.s

# target to generate assembly for a file
src/Iluminacao/Iluminacao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Iluminacao/Iluminacao.cpp.s
.PHONY : src/Iluminacao/Iluminacao.cpp.s

src/Malha/Malha.o: src/Malha/Malha.cpp.o
.PHONY : src/Malha/Malha.o

# target to build an object file
src/Malha/Malha.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Malha/Malha.cpp.o
.PHONY : src/Malha/Malha.cpp.o

src/Malha/Malha.i: src/Malha/Malha.cpp.i
.PHONY : src/Malha/Malha.i

# target to preprocess a source file
src/Malha/Malha.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Malha/Malha.cpp.i
.PHONY : src/Malha/Malha.cpp.i

src/Malha/Malha.s: src/Malha/Malha.cpp.s
.PHONY : src/Malha/Malha.s

# target to generate assembly for a file
src/Malha/Malha.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Malha/Malha.cpp.s
.PHONY : src/Malha/Malha.cpp.s

src/Material/Material.o: src/Material/Material.cpp.o
.PHONY : src/Material/Material.o

# target to build an object file
src/Material/Material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Material/Material.cpp.o
.PHONY : src/Material/Material.cpp.o

src/Material/Material.i: src/Material/Material.cpp.i
.PHONY : src/Material/Material.i

# target to preprocess a source file
src/Material/Material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Material/Material.cpp.i
.PHONY : src/Material/Material.cpp.i

src/Material/Material.s: src/Material/Material.cpp.s
.PHONY : src/Material/Material.s

# target to generate assembly for a file
src/Material/Material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Material/Material.cpp.s
.PHONY : src/Material/Material.cpp.s

src/Objeto/Objeto.o: src/Objeto/Objeto.cpp.o
.PHONY : src/Objeto/Objeto.o

# target to build an object file
src/Objeto/Objeto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Objeto/Objeto.cpp.o
.PHONY : src/Objeto/Objeto.cpp.o

src/Objeto/Objeto.i: src/Objeto/Objeto.cpp.i
.PHONY : src/Objeto/Objeto.i

# target to preprocess a source file
src/Objeto/Objeto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Objeto/Objeto.cpp.i
.PHONY : src/Objeto/Objeto.cpp.i

src/Objeto/Objeto.s: src/Objeto/Objeto.cpp.s
.PHONY : src/Objeto/Objeto.s

# target to generate assembly for a file
src/Objeto/Objeto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Objeto/Objeto.cpp.s
.PHONY : src/Objeto/Objeto.cpp.s

src/ObjetoComplexo/ObjetoComplexo.o: src/ObjetoComplexo/ObjetoComplexo.cpp.o
.PHONY : src/ObjetoComplexo/ObjetoComplexo.o

# target to build an object file
src/ObjetoComplexo/ObjetoComplexo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/ObjetoComplexo/ObjetoComplexo.cpp.o
.PHONY : src/ObjetoComplexo/ObjetoComplexo.cpp.o

src/ObjetoComplexo/ObjetoComplexo.i: src/ObjetoComplexo/ObjetoComplexo.cpp.i
.PHONY : src/ObjetoComplexo/ObjetoComplexo.i

# target to preprocess a source file
src/ObjetoComplexo/ObjetoComplexo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/ObjetoComplexo/ObjetoComplexo.cpp.i
.PHONY : src/ObjetoComplexo/ObjetoComplexo.cpp.i

src/ObjetoComplexo/ObjetoComplexo.s: src/ObjetoComplexo/ObjetoComplexo.cpp.s
.PHONY : src/ObjetoComplexo/ObjetoComplexo.s

# target to generate assembly for a file
src/ObjetoComplexo/ObjetoComplexo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/ObjetoComplexo/ObjetoComplexo.cpp.s
.PHONY : src/ObjetoComplexo/ObjetoComplexo.cpp.s

src/Plano/Plano.o: src/Plano/Plano.cpp.o
.PHONY : src/Plano/Plano.o

# target to build an object file
src/Plano/Plano.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Plano/Plano.cpp.o
.PHONY : src/Plano/Plano.cpp.o

src/Plano/Plano.i: src/Plano/Plano.cpp.i
.PHONY : src/Plano/Plano.i

# target to preprocess a source file
src/Plano/Plano.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Plano/Plano.cpp.i
.PHONY : src/Plano/Plano.cpp.i

src/Plano/Plano.s: src/Plano/Plano.cpp.s
.PHONY : src/Plano/Plano.s

# target to generate assembly for a file
src/Plano/Plano.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Plano/Plano.cpp.s
.PHONY : src/Plano/Plano.cpp.s

src/PlanoTextura/PlanoTextura.o: src/PlanoTextura/PlanoTextura.cpp.o
.PHONY : src/PlanoTextura/PlanoTextura.o

# target to build an object file
src/PlanoTextura/PlanoTextura.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/PlanoTextura/PlanoTextura.cpp.o
.PHONY : src/PlanoTextura/PlanoTextura.cpp.o

src/PlanoTextura/PlanoTextura.i: src/PlanoTextura/PlanoTextura.cpp.i
.PHONY : src/PlanoTextura/PlanoTextura.i

# target to preprocess a source file
src/PlanoTextura/PlanoTextura.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/PlanoTextura/PlanoTextura.cpp.i
.PHONY : src/PlanoTextura/PlanoTextura.cpp.i

src/PlanoTextura/PlanoTextura.s: src/PlanoTextura/PlanoTextura.cpp.s
.PHONY : src/PlanoTextura/PlanoTextura.s

# target to generate assembly for a file
src/PlanoTextura/PlanoTextura.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/PlanoTextura/PlanoTextura.cpp.s
.PHONY : src/PlanoTextura/PlanoTextura.cpp.s

src/Ponto/Ponto.o: src/Ponto/Ponto.cpp.o
.PHONY : src/Ponto/Ponto.o

# target to build an object file
src/Ponto/Ponto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Ponto/Ponto.cpp.o
.PHONY : src/Ponto/Ponto.cpp.o

src/Ponto/Ponto.i: src/Ponto/Ponto.cpp.i
.PHONY : src/Ponto/Ponto.i

# target to preprocess a source file
src/Ponto/Ponto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Ponto/Ponto.cpp.i
.PHONY : src/Ponto/Ponto.cpp.i

src/Ponto/Ponto.s: src/Ponto/Ponto.cpp.s
.PHONY : src/Ponto/Ponto.s

# target to generate assembly for a file
src/Ponto/Ponto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Ponto/Ponto.cpp.s
.PHONY : src/Ponto/Ponto.cpp.s

src/Raio/Raio.o: src/Raio/Raio.cpp.o
.PHONY : src/Raio/Raio.o

# target to build an object file
src/Raio/Raio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Raio/Raio.cpp.o
.PHONY : src/Raio/Raio.cpp.o

src/Raio/Raio.i: src/Raio/Raio.cpp.i
.PHONY : src/Raio/Raio.i

# target to preprocess a source file
src/Raio/Raio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Raio/Raio.cpp.i
.PHONY : src/Raio/Raio.cpp.i

src/Raio/Raio.s: src/Raio/Raio.cpp.s
.PHONY : src/Raio/Raio.s

# target to generate assembly for a file
src/Raio/Raio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Raio/Raio.cpp.s
.PHONY : src/Raio/Raio.cpp.s

src/Textura/Textura.o: src/Textura/Textura.cpp.o
.PHONY : src/Textura/Textura.o

# target to build an object file
src/Textura/Textura.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Textura/Textura.cpp.o
.PHONY : src/Textura/Textura.cpp.o

src/Textura/Textura.i: src/Textura/Textura.cpp.i
.PHONY : src/Textura/Textura.i

# target to preprocess a source file
src/Textura/Textura.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Textura/Textura.cpp.i
.PHONY : src/Textura/Textura.cpp.i

src/Textura/Textura.s: src/Textura/Textura.cpp.s
.PHONY : src/Textura/Textura.s

# target to generate assembly for a file
src/Textura/Textura.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Textura/Textura.cpp.s
.PHONY : src/Textura/Textura.cpp.s

src/Triangulo/Triangulo.o: src/Triangulo/Triangulo.cpp.o
.PHONY : src/Triangulo/Triangulo.o

# target to build an object file
src/Triangulo/Triangulo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Triangulo/Triangulo.cpp.o
.PHONY : src/Triangulo/Triangulo.cpp.o

src/Triangulo/Triangulo.i: src/Triangulo/Triangulo.cpp.i
.PHONY : src/Triangulo/Triangulo.i

# target to preprocess a source file
src/Triangulo/Triangulo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Triangulo/Triangulo.cpp.i
.PHONY : src/Triangulo/Triangulo.cpp.i

src/Triangulo/Triangulo.s: src/Triangulo/Triangulo.cpp.s
.PHONY : src/Triangulo/Triangulo.s

# target to generate assembly for a file
src/Triangulo/Triangulo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/Triangulo/Triangulo.cpp.s
.PHONY : src/Triangulo/Triangulo.cpp.s

src/calcular_intersecao.o: src/calcular_intersecao.cpp.o
.PHONY : src/calcular_intersecao.o

# target to build an object file
src/calcular_intersecao.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/calcular_intersecao.cpp.o
.PHONY : src/calcular_intersecao.cpp.o

src/calcular_intersecao.i: src/calcular_intersecao.cpp.i
.PHONY : src/calcular_intersecao.i

# target to preprocess a source file
src/calcular_intersecao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/calcular_intersecao.cpp.i
.PHONY : src/calcular_intersecao.cpp.i

src/calcular_intersecao.s: src/calcular_intersecao.cpp.s
.PHONY : src/calcular_intersecao.s

# target to generate assembly for a file
src/calcular_intersecao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/calcular_intersecao.cpp.s
.PHONY : src/calcular_intersecao.cpp.s

src/inicializar_objetos.o: src/inicializar_objetos.cpp.o
.PHONY : src/inicializar_objetos.o

# target to build an object file
src/inicializar_objetos.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/inicializar_objetos.cpp.o
.PHONY : src/inicializar_objetos.cpp.o

src/inicializar_objetos.i: src/inicializar_objetos.cpp.i
.PHONY : src/inicializar_objetos.i

# target to preprocess a source file
src/inicializar_objetos.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/inicializar_objetos.cpp.i
.PHONY : src/inicializar_objetos.cpp.i

src/inicializar_objetos.s: src/inicializar_objetos.cpp.s
.PHONY : src/inicializar_objetos.s

# target to generate assembly for a file
src/inicializar_objetos.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/inicializar_objetos.cpp.s
.PHONY : src/inicializar_objetos.cpp.s

src/objetosTrabalhofinal.o: src/objetosTrabalhofinal.cpp.o
.PHONY : src/objetosTrabalhofinal.o

# target to build an object file
src/objetosTrabalhofinal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/objetosTrabalhofinal.cpp.o
.PHONY : src/objetosTrabalhofinal.cpp.o

src/objetosTrabalhofinal.i: src/objetosTrabalhofinal.cpp.i
.PHONY : src/objetosTrabalhofinal.i

# target to preprocess a source file
src/objetosTrabalhofinal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/objetosTrabalhofinal.cpp.i
.PHONY : src/objetosTrabalhofinal.cpp.i

src/objetosTrabalhofinal.s: src/objetosTrabalhofinal.cpp.s
.PHONY : src/objetosTrabalhofinal.s

# target to generate assembly for a file
src/objetosTrabalhofinal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CG_Creto_work.dir/build.make CMakeFiles/CG_Creto_work.dir/src/objetosTrabalhofinal.cpp.s
.PHONY : src/objetosTrabalhofinal.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... update_mappings"
	@echo "... CG_Creto_work"
	@echo "... glfw"
	@echo "... raylib"
	@echo "... Algebra.o"
	@echo "... Algebra.i"
	@echo "... Algebra.s"
	@echo "... bin/Trabalho_Final.o"
	@echo "... bin/Trabalho_Final.i"
	@echo "... bin/Trabalho_Final.s"
	@echo "... src/Aresta/Aresta.o"
	@echo "... src/Aresta/Aresta.i"
	@echo "... src/Aresta/Aresta.s"
	@echo "... src/Camera/Camera.o"
	@echo "... src/Camera/Camera.i"
	@echo "... src/Camera/Camera.s"
	@echo "... src/Cilindro/Cilindro.o"
	@echo "... src/Cilindro/Cilindro.i"
	@echo "... src/Cilindro/Cilindro.s"
	@echo "... src/Circulo/Circulo.o"
	@echo "... src/Circulo/Circulo.i"
	@echo "... src/Circulo/Circulo.s"
	@echo "... src/Cone/Cone.o"
	@echo "... src/Cone/Cone.i"
	@echo "... src/Cone/Cone.s"
	@echo "... src/Esfera/Esfera.o"
	@echo "... src/Esfera/Esfera.i"
	@echo "... src/Esfera/Esfera.s"
	@echo "... src/Iluminacao/Iluminacao.o"
	@echo "... src/Iluminacao/Iluminacao.i"
	@echo "... src/Iluminacao/Iluminacao.s"
	@echo "... src/Malha/Malha.o"
	@echo "... src/Malha/Malha.i"
	@echo "... src/Malha/Malha.s"
	@echo "... src/Material/Material.o"
	@echo "... src/Material/Material.i"
	@echo "... src/Material/Material.s"
	@echo "... src/Objeto/Objeto.o"
	@echo "... src/Objeto/Objeto.i"
	@echo "... src/Objeto/Objeto.s"
	@echo "... src/ObjetoComplexo/ObjetoComplexo.o"
	@echo "... src/ObjetoComplexo/ObjetoComplexo.i"
	@echo "... src/ObjetoComplexo/ObjetoComplexo.s"
	@echo "... src/Plano/Plano.o"
	@echo "... src/Plano/Plano.i"
	@echo "... src/Plano/Plano.s"
	@echo "... src/PlanoTextura/PlanoTextura.o"
	@echo "... src/PlanoTextura/PlanoTextura.i"
	@echo "... src/PlanoTextura/PlanoTextura.s"
	@echo "... src/Ponto/Ponto.o"
	@echo "... src/Ponto/Ponto.i"
	@echo "... src/Ponto/Ponto.s"
	@echo "... src/Raio/Raio.o"
	@echo "... src/Raio/Raio.i"
	@echo "... src/Raio/Raio.s"
	@echo "... src/Textura/Textura.o"
	@echo "... src/Textura/Textura.i"
	@echo "... src/Textura/Textura.s"
	@echo "... src/Triangulo/Triangulo.o"
	@echo "... src/Triangulo/Triangulo.i"
	@echo "... src/Triangulo/Triangulo.s"
	@echo "... src/calcular_intersecao.o"
	@echo "... src/calcular_intersecao.i"
	@echo "... src/calcular_intersecao.s"
	@echo "... src/inicializar_objetos.o"
	@echo "... src/inicializar_objetos.i"
	@echo "... src/inicializar_objetos.s"
	@echo "... src/objetosTrabalhofinal.o"
	@echo "... src/objetosTrabalhofinal.i"
	@echo "... src/objetosTrabalhofinal.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

